services:
  api:
    build:
      dockerfile: api/Dockerfile
    restart: on-failure
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - influxdb
    env_file:
      - .env

  jupyter_notebook:
    build:
      dockerfile: notebook/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./notebook:/home/jovyan/notebook
      - ./data:/home/jovyan/data
      - .env:/home/jovyan/.env

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  influxdb:
    image: influxdb
    restart: always
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

volumes:
  postgres:
  influxdb:
