version: '3.9'
services:
  frontend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - env/frontend.env
    volumes: 
      - data:/data

  api:
    image: swoop-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '5000:80'
    depends_on:
      - postgres
      - influxdb
    env_file:
      - env/influxdb.env
      - env/postgres.env


  postgres:
    image: postgres
    restart: always
    env_file:
      - env/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb: 
    image: influxdb
    restart: always
    env_file:
      - env/influxdb.env
    ports:
      - '8086:8086'
    volumes: 
      - influxdb_data:/var/lib/influxdb


volumes: 
  data:
  postgres_data:
  influxdb_data:
  grafana_data:
