version: '3.9'
services:
  frontend:
    build: 
      context: ./
    ports:
      - 5000:80
    environment:
      - TOKEN=${TOKEN}
    volumes: 
      - data:/data

  influxdb: 
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment: 
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - 8086:8086
    volumes: 
      - influxdb_data:/var/lib/influxdb

  grafana: 
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment: 
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - 3000:3000
    volumes: 
      - grafana_data:/var/lib/grafana


volumes: 
  data:
  influxdb_data:
  grafana_data:
