version: '3.9'
services:
  api:
    image: swoop-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '5000:80'
    depends_on:
      - postgres
      - influxdb
    env_file:
      - env/.env

  jupyter_notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
    volumes:
      - ./notebook:/home/jovyan/notebook
      - ./data:/home/jovyan/data

  postgres:
    image: postgres
    restart: always
    env_file:
      - env/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  influxdb: 
    image: influxdb
    restart: always
    env_file:
      - env/.env
    ports:
      - '8086:8086'
    volumes: 
      - influxdb:/var/lib/influxdb

volumes: 
  postgres:
  influxdb:
