version: '3.9'
services:
  frontend:
    build: 
      context: ./
    ports:
      - '5000:80'
    environment:
      - TOKEN=${TOKEN}
    volumes: 
      - data:/data

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb: 
    image: influxdb
    restart: always
    environment: 
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
    ports:
      - '8086:8086'
    volumes: 
      - influxdb_data:/var/lib/influxdb


volumes: 
  data:
  postgres_data:
  influxdb_data:
  grafana_data:
